[package]
name = "WaltonProxy"
version = "0.1.0"
authors = ["René Meyer <36350532+BuggerSee@users.noreply.github.com>"]

[dependencies]
ansi_term = "0.11"
byteorder = "1.2.3"
rand = "0.5.2"
clap = "2.32.0"